name: SRP
version: ${project.version}
author: Fx-Costa
main: com.fx.srp.SpeedRunPlus
api-version: 1.16
depend:
  - Multiverse-Core
  - Multiverse-NetherPortals

permissions:
  # Admin commands
  srp.admin:
    description: Bypass any restrictions & access to admin tools
    default: false

  # General
  srp.use:
    description: Allows overall usage of /srp
    default: true

  # Game modes
  srp.solo:
    description: Allows usage of the solo game mode
    default: true

  srp.battle:
    description: Allows usage of the battle game mode
    default: true

  srp.coop:
    description: Allows usage of the coop game mode
    default: true
